title: TBC
description: TBC
theme: just-the-docs

url: https://archivesserver.github.io

logo: "/assets/images/logo512.png"
favicon_ico: "/assets/images/favicon.ico"

color_scheme: foo

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
