title: TBC
description: TBC
theme: just-the-docs

url: https://archivesserver.github.io

logo: "/assets/images/logo512.png"
favicon_ico: "/assets/images/favicon.ico"

color_scheme: foo

nav_enabled: true

aux_links:
  Github: https://github.com/ArchivesServer/archivesserver.github.io
