title: TBC
description: TBC
theme: just-the-docs

url: https://archivesserver.github.io

logo: "/assets/images/logo512.png"
favicon_ico: "/assets/images/favicon.ico"

color_scheme: foo

nav_enabled: true

aux_links:
  Github: https://github.com/ArchivesServer/archivesserver.github.io

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: purple
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
